language: android
jdk: oraclejdk8
sudo: false

env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - EMU_FLAVOR=default # use google_apis flavor if no default flavor emulator
    matrix:
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a

before_install:
 - chmod +x gradlew

 - touch $HOME/.android/repositories.cfg
 - yes | sdkmanager "platforms;android-28"
 - yes | sdkmanager "build-tools;28.0.3"

 - yes | sdkmanager tools
 - sdkmanager "system-images;android-$ANDROID_TARGET;$EMU_FLAVOR;$ANDROID_ABI"

 - echo no | avdmanager create avd --force -n test -k "system-images;android-$ANDROID_TARGET;$EMU_FLAVOR;$ANDROID_ABI -c 10M"
 - $ANDROID_HOME/emulator/emulator -avd test -engine classic -no-window $AUDIO -camera-back none -camera-front none -selinux permissive -qemu -m 512 &

install: ./gradlew clean assemble --stacktrace

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-22
    - android-$ANDROID_TARGET

    # Additional components
    #- extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_script:
    - android-wait-for-emulator
    - adb shell settings put global window_animation_scale 0 &
    - adb shell settings put global transition_animation_scale 0 &
    - adb shell settings put global animator_duration_scale 0 &
    - adb shell input keyevent 82 &

script:
    - ./gradlew build jacocoTestReport assembleAndroidTest
    - ./gradlew connectedAndroidTest
    - ./gradlew connectedCheck

after_success:
    - bash <(curl -s https://codecov.io/bash)